// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipfs_lite.proto

package ipfs_lite

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddParams struct {
	Layout               string   `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
	Chunker              string   `protobuf:"bytes,2,opt,name=chunker,proto3" json:"chunker,omitempty"`
	RawLeaves            bool     `protobuf:"varint,3,opt,name=rawLeaves,proto3" json:"rawLeaves,omitempty"`
	Hidden               bool     `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Shared               bool     `protobuf:"varint,5,opt,name=shared,proto3" json:"shared,omitempty"`
	NoCopy               bool     `protobuf:"varint,6,opt,name=noCopy,proto3" json:"noCopy,omitempty"`
	HashFun              string   `protobuf:"bytes,7,opt,name=hashFun,proto3" json:"hashFun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddParams) Reset()         { *m = AddParams{} }
func (m *AddParams) String() string { return proto.CompactTextString(m) }
func (*AddParams) ProtoMessage()    {}
func (*AddParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{0}
}

func (m *AddParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddParams.Unmarshal(m, b)
}
func (m *AddParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddParams.Marshal(b, m, deterministic)
}
func (m *AddParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddParams.Merge(m, src)
}
func (m *AddParams) XXX_Size() int {
	return xxx_messageInfo_AddParams.Size(m)
}
func (m *AddParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddParams proto.InternalMessageInfo

func (m *AddParams) GetLayout() string {
	if m != nil {
		return m.Layout
	}
	return ""
}

func (m *AddParams) GetChunker() string {
	if m != nil {
		return m.Chunker
	}
	return ""
}

func (m *AddParams) GetRawLeaves() bool {
	if m != nil {
		return m.RawLeaves
	}
	return false
}

func (m *AddParams) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *AddParams) GetShared() bool {
	if m != nil {
		return m.Shared
	}
	return false
}

func (m *AddParams) GetNoCopy() bool {
	if m != nil {
		return m.NoCopy
	}
	return false
}

func (m *AddParams) GetHashFun() string {
	if m != nil {
		return m.HashFun
	}
	return ""
}

type Block struct {
	RawData              []byte   `protobuf:"bytes,1,opt,name=rawData,proto3" json:"rawData,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetRawData() []byte {
	if m != nil {
		return m.RawData
	}
	return nil
}

func (m *Block) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type Link struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Cid                  string   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{2}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Link) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Link) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type NodeStat struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	NumLinks             int32    `protobuf:"varint,2,opt,name=numLinks,proto3" json:"numLinks,omitempty"`
	BlockSize            int32    `protobuf:"varint,3,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	LinksSize            int32    `protobuf:"varint,4,opt,name=linksSize,proto3" json:"linksSize,omitempty"`
	DataSize             int32    `protobuf:"varint,5,opt,name=dataSize,proto3" json:"dataSize,omitempty"`
	CumulativeSize       int32    `protobuf:"varint,6,opt,name=cumulativeSize,proto3" json:"cumulativeSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStat) Reset()         { *m = NodeStat{} }
func (m *NodeStat) String() string { return proto.CompactTextString(m) }
func (*NodeStat) ProtoMessage()    {}
func (*NodeStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{3}
}

func (m *NodeStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStat.Unmarshal(m, b)
}
func (m *NodeStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStat.Marshal(b, m, deterministic)
}
func (m *NodeStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStat.Merge(m, src)
}
func (m *NodeStat) XXX_Size() int {
	return xxx_messageInfo_NodeStat.Size(m)
}
func (m *NodeStat) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStat.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStat proto.InternalMessageInfo

func (m *NodeStat) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *NodeStat) GetNumLinks() int32 {
	if m != nil {
		return m.NumLinks
	}
	return 0
}

func (m *NodeStat) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

func (m *NodeStat) GetLinksSize() int32 {
	if m != nil {
		return m.LinksSize
	}
	return 0
}

func (m *NodeStat) GetDataSize() int32 {
	if m != nil {
		return m.DataSize
	}
	return 0
}

func (m *NodeStat) GetCumulativeSize() int32 {
	if m != nil {
		return m.CumulativeSize
	}
	return 0
}

type Node struct {
	Block                *Block    `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Links                []*Link   `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	Stat                 *NodeStat `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`
	Size                 int64     `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{4}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Node) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Node) GetStat() *NodeStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *Node) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type AddFileRequest struct {
	AddParams            *AddParams `protobuf:"bytes,1,opt,name=addParams,proto3" json:"addParams,omitempty"`
	Data                 []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddFileRequest) Reset()         { *m = AddFileRequest{} }
func (m *AddFileRequest) String() string { return proto.CompactTextString(m) }
func (*AddFileRequest) ProtoMessage()    {}
func (*AddFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{5}
}

func (m *AddFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFileRequest.Unmarshal(m, b)
}
func (m *AddFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFileRequest.Marshal(b, m, deterministic)
}
func (m *AddFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFileRequest.Merge(m, src)
}
func (m *AddFileRequest) XXX_Size() int {
	return xxx_messageInfo_AddFileRequest.Size(m)
}
func (m *AddFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFileRequest proto.InternalMessageInfo

func (m *AddFileRequest) GetAddParams() *AddParams {
	if m != nil {
		return m.AddParams
	}
	return nil
}

func (m *AddFileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddFileResponse struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFileResponse) Reset()         { *m = AddFileResponse{} }
func (m *AddFileResponse) String() string { return proto.CompactTextString(m) }
func (*AddFileResponse) ProtoMessage()    {}
func (*AddFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{6}
}

func (m *AddFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFileResponse.Unmarshal(m, b)
}
func (m *AddFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFileResponse.Marshal(b, m, deterministic)
}
func (m *AddFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFileResponse.Merge(m, src)
}
func (m *AddFileResponse) XXX_Size() int {
	return xxx_messageInfo_AddFileResponse.Size(m)
}
func (m *AddFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFileResponse proto.InternalMessageInfo

func (m *AddFileResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetFileRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileRequest) Reset()         { *m = GetFileRequest{} }
func (m *GetFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileRequest) ProtoMessage()    {}
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{7}
}

func (m *GetFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileRequest.Unmarshal(m, b)
}
func (m *GetFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileRequest.Marshal(b, m, deterministic)
}
func (m *GetFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileRequest.Merge(m, src)
}
func (m *GetFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileRequest.Size(m)
}
func (m *GetFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileRequest proto.InternalMessageInfo

func (m *GetFileRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type GetFileResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileResponse) Reset()         { *m = GetFileResponse{} }
func (m *GetFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetFileResponse) ProtoMessage()    {}
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{8}
}

func (m *GetFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileResponse.Unmarshal(m, b)
}
func (m *GetFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileResponse.Marshal(b, m, deterministic)
}
func (m *GetFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileResponse.Merge(m, src)
}
func (m *GetFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetFileResponse.Size(m)
}
func (m *GetFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileResponse proto.InternalMessageInfo

func (m *GetFileResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddNodeRequest struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeRequest) Reset()         { *m = AddNodeRequest{} }
func (m *AddNodeRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodeRequest) ProtoMessage()    {}
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{9}
}

func (m *AddNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeRequest.Unmarshal(m, b)
}
func (m *AddNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeRequest.Marshal(b, m, deterministic)
}
func (m *AddNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeRequest.Merge(m, src)
}
func (m *AddNodeRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodeRequest.Size(m)
}
func (m *AddNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeRequest proto.InternalMessageInfo

func (m *AddNodeRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type AddNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodeResponse) Reset()         { *m = AddNodeResponse{} }
func (m *AddNodeResponse) String() string { return proto.CompactTextString(m) }
func (*AddNodeResponse) ProtoMessage()    {}
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{10}
}

func (m *AddNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeResponse.Unmarshal(m, b)
}
func (m *AddNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeResponse.Marshal(b, m, deterministic)
}
func (m *AddNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeResponse.Merge(m, src)
}
func (m *AddNodeResponse) XXX_Size() int {
	return xxx_messageInfo_AddNodeResponse.Size(m)
}
func (m *AddNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeResponse proto.InternalMessageInfo

type AddNodesRequest struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodesRequest) Reset()         { *m = AddNodesRequest{} }
func (m *AddNodesRequest) String() string { return proto.CompactTextString(m) }
func (*AddNodesRequest) ProtoMessage()    {}
func (*AddNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{11}
}

func (m *AddNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodesRequest.Unmarshal(m, b)
}
func (m *AddNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodesRequest.Marshal(b, m, deterministic)
}
func (m *AddNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodesRequest.Merge(m, src)
}
func (m *AddNodesRequest) XXX_Size() int {
	return xxx_messageInfo_AddNodesRequest.Size(m)
}
func (m *AddNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodesRequest proto.InternalMessageInfo

func (m *AddNodesRequest) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type AddNodesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNodesResponse) Reset()         { *m = AddNodesResponse{} }
func (m *AddNodesResponse) String() string { return proto.CompactTextString(m) }
func (*AddNodesResponse) ProtoMessage()    {}
func (*AddNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{12}
}

func (m *AddNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodesResponse.Unmarshal(m, b)
}
func (m *AddNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodesResponse.Marshal(b, m, deterministic)
}
func (m *AddNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodesResponse.Merge(m, src)
}
func (m *AddNodesResponse) XXX_Size() int {
	return xxx_messageInfo_AddNodesResponse.Size(m)
}
func (m *AddNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodesResponse proto.InternalMessageInfo

type GetNodeRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{13}
}

func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(m, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type GetNodeResponse struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeResponse) Reset()         { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()    {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{14}
}

func (m *GetNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeResponse.Unmarshal(m, b)
}
func (m *GetNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeResponse.Merge(m, src)
}
func (m *GetNodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeResponse.Size(m)
}
func (m *GetNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeResponse proto.InternalMessageInfo

func (m *GetNodeResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetNodesRequest struct {
	Cids                 []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesRequest) Reset()         { *m = GetNodesRequest{} }
func (m *GetNodesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodesRequest) ProtoMessage()    {}
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{15}
}

func (m *GetNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesRequest.Unmarshal(m, b)
}
func (m *GetNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesRequest.Marshal(b, m, deterministic)
}
func (m *GetNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesRequest.Merge(m, src)
}
func (m *GetNodesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodesRequest.Size(m)
}
func (m *GetNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesRequest proto.InternalMessageInfo

func (m *GetNodesRequest) GetCids() []string {
	if m != nil {
		return m.Cids
	}
	return nil
}

type GetNodesResponse struct {
	// Types that are valid to be assigned to Option:
	//	*GetNodesResponse_Node
	//	*GetNodesResponse_Error
	Option               isGetNodesResponse_Option `protobuf_oneof:"option"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetNodesResponse) Reset()         { *m = GetNodesResponse{} }
func (m *GetNodesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodesResponse) ProtoMessage()    {}
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{16}
}

func (m *GetNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesResponse.Unmarshal(m, b)
}
func (m *GetNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesResponse.Marshal(b, m, deterministic)
}
func (m *GetNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesResponse.Merge(m, src)
}
func (m *GetNodesResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodesResponse.Size(m)
}
func (m *GetNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesResponse proto.InternalMessageInfo

type isGetNodesResponse_Option interface {
	isGetNodesResponse_Option()
}

type GetNodesResponse_Node struct {
	Node *Node `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type GetNodesResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetNodesResponse_Node) isGetNodesResponse_Option() {}

func (*GetNodesResponse_Error) isGetNodesResponse_Option() {}

func (m *GetNodesResponse) GetOption() isGetNodesResponse_Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *GetNodesResponse) GetNode() *Node {
	if x, ok := m.GetOption().(*GetNodesResponse_Node); ok {
		return x.Node
	}
	return nil
}

func (m *GetNodesResponse) GetError() string {
	if x, ok := m.GetOption().(*GetNodesResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetNodesResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetNodesResponse_Node)(nil),
		(*GetNodesResponse_Error)(nil),
	}
}

type RemoveNodeRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeRequest) Reset()         { *m = RemoveNodeRequest{} }
func (m *RemoveNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeRequest) ProtoMessage()    {}
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{17}
}

func (m *RemoveNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeRequest.Unmarshal(m, b)
}
func (m *RemoveNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeRequest.Merge(m, src)
}
func (m *RemoveNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeRequest.Size(m)
}
func (m *RemoveNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeRequest proto.InternalMessageInfo

func (m *RemoveNodeRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type RemoveNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodeResponse) Reset()         { *m = RemoveNodeResponse{} }
func (m *RemoveNodeResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveNodeResponse) ProtoMessage()    {}
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{18}
}

func (m *RemoveNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodeResponse.Unmarshal(m, b)
}
func (m *RemoveNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodeResponse.Marshal(b, m, deterministic)
}
func (m *RemoveNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodeResponse.Merge(m, src)
}
func (m *RemoveNodeResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveNodeResponse.Size(m)
}
func (m *RemoveNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodeResponse proto.InternalMessageInfo

type RemoveNodesRequest struct {
	Cids                 []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodesRequest) Reset()         { *m = RemoveNodesRequest{} }
func (m *RemoveNodesRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNodesRequest) ProtoMessage()    {}
func (*RemoveNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{19}
}

func (m *RemoveNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodesRequest.Unmarshal(m, b)
}
func (m *RemoveNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodesRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodesRequest.Merge(m, src)
}
func (m *RemoveNodesRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNodesRequest.Size(m)
}
func (m *RemoveNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodesRequest proto.InternalMessageInfo

func (m *RemoveNodesRequest) GetCids() []string {
	if m != nil {
		return m.Cids
	}
	return nil
}

type RemoveNodesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNodesResponse) Reset()         { *m = RemoveNodesResponse{} }
func (m *RemoveNodesResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveNodesResponse) ProtoMessage()    {}
func (*RemoveNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{20}
}

func (m *RemoveNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNodesResponse.Unmarshal(m, b)
}
func (m *RemoveNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNodesResponse.Marshal(b, m, deterministic)
}
func (m *RemoveNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNodesResponse.Merge(m, src)
}
func (m *RemoveNodesResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveNodesResponse.Size(m)
}
func (m *RemoveNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNodesResponse proto.InternalMessageInfo

type ResolveLinkRequest struct {
	NodeCid              string   `protobuf:"bytes,1,opt,name=nodeCid,proto3" json:"nodeCid,omitempty"`
	Path                 []string `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveLinkRequest) Reset()         { *m = ResolveLinkRequest{} }
func (m *ResolveLinkRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveLinkRequest) ProtoMessage()    {}
func (*ResolveLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{21}
}

func (m *ResolveLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveLinkRequest.Unmarshal(m, b)
}
func (m *ResolveLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveLinkRequest.Marshal(b, m, deterministic)
}
func (m *ResolveLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveLinkRequest.Merge(m, src)
}
func (m *ResolveLinkRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveLinkRequest.Size(m)
}
func (m *ResolveLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveLinkRequest proto.InternalMessageInfo

func (m *ResolveLinkRequest) GetNodeCid() string {
	if m != nil {
		return m.NodeCid
	}
	return ""
}

func (m *ResolveLinkRequest) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type ResolveLinkResponse struct {
	Link                 *Link    `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	RemainingPath        []string `protobuf:"bytes,2,rep,name=remainingPath,proto3" json:"remainingPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveLinkResponse) Reset()         { *m = ResolveLinkResponse{} }
func (m *ResolveLinkResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveLinkResponse) ProtoMessage()    {}
func (*ResolveLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{22}
}

func (m *ResolveLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveLinkResponse.Unmarshal(m, b)
}
func (m *ResolveLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveLinkResponse.Marshal(b, m, deterministic)
}
func (m *ResolveLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveLinkResponse.Merge(m, src)
}
func (m *ResolveLinkResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveLinkResponse.Size(m)
}
func (m *ResolveLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveLinkResponse proto.InternalMessageInfo

func (m *ResolveLinkResponse) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *ResolveLinkResponse) GetRemainingPath() []string {
	if m != nil {
		return m.RemainingPath
	}
	return nil
}

type ResolveRequest struct {
	NodeCid              string   `protobuf:"bytes,1,opt,name=nodeCid,proto3" json:"nodeCid,omitempty"`
	Path                 []string `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveRequest) Reset()         { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()    {}
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{23}
}

func (m *ResolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveRequest.Unmarshal(m, b)
}
func (m *ResolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveRequest.Marshal(b, m, deterministic)
}
func (m *ResolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveRequest.Merge(m, src)
}
func (m *ResolveRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveRequest.Size(m)
}
func (m *ResolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveRequest proto.InternalMessageInfo

func (m *ResolveRequest) GetNodeCid() string {
	if m != nil {
		return m.NodeCid
	}
	return ""
}

func (m *ResolveRequest) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type ResolveResponse struct {
	Object               *any.Any `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	RemainingPath        []string `protobuf:"bytes,2,rep,name=remainingPath,proto3" json:"remainingPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveResponse) Reset()         { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()    {}
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{24}
}

func (m *ResolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveResponse.Unmarshal(m, b)
}
func (m *ResolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveResponse.Marshal(b, m, deterministic)
}
func (m *ResolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveResponse.Merge(m, src)
}
func (m *ResolveResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveResponse.Size(m)
}
func (m *ResolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveResponse proto.InternalMessageInfo

func (m *ResolveResponse) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *ResolveResponse) GetRemainingPath() []string {
	if m != nil {
		return m.RemainingPath
	}
	return nil
}

type TreeRequest struct {
	NodeCid              string   `protobuf:"bytes,1,opt,name=nodeCid,proto3" json:"nodeCid,omitempty"`
	Path                 []string `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	Depth                int32    `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeRequest) Reset()         { *m = TreeRequest{} }
func (m *TreeRequest) String() string { return proto.CompactTextString(m) }
func (*TreeRequest) ProtoMessage()    {}
func (*TreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{25}
}

func (m *TreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeRequest.Unmarshal(m, b)
}
func (m *TreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeRequest.Marshal(b, m, deterministic)
}
func (m *TreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeRequest.Merge(m, src)
}
func (m *TreeRequest) XXX_Size() int {
	return xxx_messageInfo_TreeRequest.Size(m)
}
func (m *TreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TreeRequest proto.InternalMessageInfo

func (m *TreeRequest) GetNodeCid() string {
	if m != nil {
		return m.NodeCid
	}
	return ""
}

func (m *TreeRequest) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *TreeRequest) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type TreeResponse struct {
	Paths                []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeResponse) Reset()         { *m = TreeResponse{} }
func (m *TreeResponse) String() string { return proto.CompactTextString(m) }
func (*TreeResponse) ProtoMessage()    {}
func (*TreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{26}
}

func (m *TreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeResponse.Unmarshal(m, b)
}
func (m *TreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeResponse.Marshal(b, m, deterministic)
}
func (m *TreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeResponse.Merge(m, src)
}
func (m *TreeResponse) XXX_Size() int {
	return xxx_messageInfo_TreeResponse.Size(m)
}
func (m *TreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TreeResponse proto.InternalMessageInfo

func (m *TreeResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type DeleteBlockRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlockRequest) Reset()         { *m = DeleteBlockRequest{} }
func (m *DeleteBlockRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBlockRequest) ProtoMessage()    {}
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{27}
}

func (m *DeleteBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlockRequest.Unmarshal(m, b)
}
func (m *DeleteBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlockRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlockRequest.Merge(m, src)
}
func (m *DeleteBlockRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBlockRequest.Size(m)
}
func (m *DeleteBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlockRequest proto.InternalMessageInfo

func (m *DeleteBlockRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type DeleteBlockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlockResponse) Reset()         { *m = DeleteBlockResponse{} }
func (m *DeleteBlockResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBlockResponse) ProtoMessage()    {}
func (*DeleteBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{28}
}

func (m *DeleteBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlockResponse.Unmarshal(m, b)
}
func (m *DeleteBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlockResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlockResponse.Merge(m, src)
}
func (m *DeleteBlockResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBlockResponse.Size(m)
}
func (m *DeleteBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlockResponse proto.InternalMessageInfo

type HasBlockRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasBlockRequest) Reset()         { *m = HasBlockRequest{} }
func (m *HasBlockRequest) String() string { return proto.CompactTextString(m) }
func (*HasBlockRequest) ProtoMessage()    {}
func (*HasBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{29}
}

func (m *HasBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasBlockRequest.Unmarshal(m, b)
}
func (m *HasBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasBlockRequest.Marshal(b, m, deterministic)
}
func (m *HasBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasBlockRequest.Merge(m, src)
}
func (m *HasBlockRequest) XXX_Size() int {
	return xxx_messageInfo_HasBlockRequest.Size(m)
}
func (m *HasBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HasBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HasBlockRequest proto.InternalMessageInfo

func (m *HasBlockRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type HasBlockResponse struct {
	HasBlock             bool     `protobuf:"varint,1,opt,name=hasBlock,proto3" json:"hasBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasBlockResponse) Reset()         { *m = HasBlockResponse{} }
func (m *HasBlockResponse) String() string { return proto.CompactTextString(m) }
func (*HasBlockResponse) ProtoMessage()    {}
func (*HasBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{30}
}

func (m *HasBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasBlockResponse.Unmarshal(m, b)
}
func (m *HasBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasBlockResponse.Marshal(b, m, deterministic)
}
func (m *HasBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasBlockResponse.Merge(m, src)
}
func (m *HasBlockResponse) XXX_Size() int {
	return xxx_messageInfo_HasBlockResponse.Size(m)
}
func (m *HasBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasBlockResponse proto.InternalMessageInfo

func (m *HasBlockResponse) GetHasBlock() bool {
	if m != nil {
		return m.HasBlock
	}
	return false
}

type GetBlockRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{31}
}

func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(m, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type GetBlockResponse struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockResponse) Reset()         { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()    {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{32}
}

func (m *GetBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponse.Unmarshal(m, b)
}
func (m *GetBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponse.Merge(m, src)
}
func (m *GetBlockResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponse.Size(m)
}
func (m *GetBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponse proto.InternalMessageInfo

func (m *GetBlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetBlockSizeRequest struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockSizeRequest) Reset()         { *m = GetBlockSizeRequest{} }
func (m *GetBlockSizeRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockSizeRequest) ProtoMessage()    {}
func (*GetBlockSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{33}
}

func (m *GetBlockSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockSizeRequest.Unmarshal(m, b)
}
func (m *GetBlockSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockSizeRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockSizeRequest.Merge(m, src)
}
func (m *GetBlockSizeRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockSizeRequest.Size(m)
}
func (m *GetBlockSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockSizeRequest proto.InternalMessageInfo

func (m *GetBlockSizeRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type GetBlockSizeResponse struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockSizeResponse) Reset()         { *m = GetBlockSizeResponse{} }
func (m *GetBlockSizeResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockSizeResponse) ProtoMessage()    {}
func (*GetBlockSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{34}
}

func (m *GetBlockSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockSizeResponse.Unmarshal(m, b)
}
func (m *GetBlockSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockSizeResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockSizeResponse.Merge(m, src)
}
func (m *GetBlockSizeResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockSizeResponse.Size(m)
}
func (m *GetBlockSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockSizeResponse proto.InternalMessageInfo

func (m *GetBlockSizeResponse) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type PutBlockRequest struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutBlockRequest) Reset()         { *m = PutBlockRequest{} }
func (m *PutBlockRequest) String() string { return proto.CompactTextString(m) }
func (*PutBlockRequest) ProtoMessage()    {}
func (*PutBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{35}
}

func (m *PutBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlockRequest.Unmarshal(m, b)
}
func (m *PutBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlockRequest.Marshal(b, m, deterministic)
}
func (m *PutBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlockRequest.Merge(m, src)
}
func (m *PutBlockRequest) XXX_Size() int {
	return xxx_messageInfo_PutBlockRequest.Size(m)
}
func (m *PutBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlockRequest proto.InternalMessageInfo

func (m *PutBlockRequest) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type PutBlockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutBlockResponse) Reset()         { *m = PutBlockResponse{} }
func (m *PutBlockResponse) String() string { return proto.CompactTextString(m) }
func (*PutBlockResponse) ProtoMessage()    {}
func (*PutBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{36}
}

func (m *PutBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlockResponse.Unmarshal(m, b)
}
func (m *PutBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlockResponse.Marshal(b, m, deterministic)
}
func (m *PutBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlockResponse.Merge(m, src)
}
func (m *PutBlockResponse) XXX_Size() int {
	return xxx_messageInfo_PutBlockResponse.Size(m)
}
func (m *PutBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlockResponse proto.InternalMessageInfo

type PutBlocksRequest struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutBlocksRequest) Reset()         { *m = PutBlocksRequest{} }
func (m *PutBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*PutBlocksRequest) ProtoMessage()    {}
func (*PutBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{37}
}

func (m *PutBlocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlocksRequest.Unmarshal(m, b)
}
func (m *PutBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlocksRequest.Marshal(b, m, deterministic)
}
func (m *PutBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlocksRequest.Merge(m, src)
}
func (m *PutBlocksRequest) XXX_Size() int {
	return xxx_messageInfo_PutBlocksRequest.Size(m)
}
func (m *PutBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlocksRequest proto.InternalMessageInfo

func (m *PutBlocksRequest) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type PutBlocksResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutBlocksResponse) Reset()         { *m = PutBlocksResponse{} }
func (m *PutBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*PutBlocksResponse) ProtoMessage()    {}
func (*PutBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{38}
}

func (m *PutBlocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutBlocksResponse.Unmarshal(m, b)
}
func (m *PutBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutBlocksResponse.Marshal(b, m, deterministic)
}
func (m *PutBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutBlocksResponse.Merge(m, src)
}
func (m *PutBlocksResponse) XXX_Size() int {
	return xxx_messageInfo_PutBlocksResponse.Size(m)
}
func (m *PutBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutBlocksResponse proto.InternalMessageInfo

type AllKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllKeysRequest) Reset()         { *m = AllKeysRequest{} }
func (m *AllKeysRequest) String() string { return proto.CompactTextString(m) }
func (*AllKeysRequest) ProtoMessage()    {}
func (*AllKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{39}
}

func (m *AllKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllKeysRequest.Unmarshal(m, b)
}
func (m *AllKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllKeysRequest.Marshal(b, m, deterministic)
}
func (m *AllKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllKeysRequest.Merge(m, src)
}
func (m *AllKeysRequest) XXX_Size() int {
	return xxx_messageInfo_AllKeysRequest.Size(m)
}
func (m *AllKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllKeysRequest proto.InternalMessageInfo

type AllKeysResponse struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllKeysResponse) Reset()         { *m = AllKeysResponse{} }
func (m *AllKeysResponse) String() string { return proto.CompactTextString(m) }
func (*AllKeysResponse) ProtoMessage()    {}
func (*AllKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{40}
}

func (m *AllKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllKeysResponse.Unmarshal(m, b)
}
func (m *AllKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllKeysResponse.Marshal(b, m, deterministic)
}
func (m *AllKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllKeysResponse.Merge(m, src)
}
func (m *AllKeysResponse) XXX_Size() int {
	return xxx_messageInfo_AllKeysResponse.Size(m)
}
func (m *AllKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllKeysResponse proto.InternalMessageInfo

func (m *AllKeysResponse) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type HashOnReadRequest struct {
	HashOnRead           bool     `protobuf:"varint,1,opt,name=hashOnRead,proto3" json:"hashOnRead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashOnReadRequest) Reset()         { *m = HashOnReadRequest{} }
func (m *HashOnReadRequest) String() string { return proto.CompactTextString(m) }
func (*HashOnReadRequest) ProtoMessage()    {}
func (*HashOnReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{41}
}

func (m *HashOnReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashOnReadRequest.Unmarshal(m, b)
}
func (m *HashOnReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashOnReadRequest.Marshal(b, m, deterministic)
}
func (m *HashOnReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashOnReadRequest.Merge(m, src)
}
func (m *HashOnReadRequest) XXX_Size() int {
	return xxx_messageInfo_HashOnReadRequest.Size(m)
}
func (m *HashOnReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashOnReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashOnReadRequest proto.InternalMessageInfo

func (m *HashOnReadRequest) GetHashOnRead() bool {
	if m != nil {
		return m.HashOnRead
	}
	return false
}

type HashOnReadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashOnReadResponse) Reset()         { *m = HashOnReadResponse{} }
func (m *HashOnReadResponse) String() string { return proto.CompactTextString(m) }
func (*HashOnReadResponse) ProtoMessage()    {}
func (*HashOnReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8edd8ce3e1de43b8, []int{42}
}

func (m *HashOnReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashOnReadResponse.Unmarshal(m, b)
}
func (m *HashOnReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashOnReadResponse.Marshal(b, m, deterministic)
}
func (m *HashOnReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashOnReadResponse.Merge(m, src)
}
func (m *HashOnReadResponse) XXX_Size() int {
	return xxx_messageInfo_HashOnReadResponse.Size(m)
}
func (m *HashOnReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashOnReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashOnReadResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddParams)(nil), "AddParams")
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Link)(nil), "Link")
	proto.RegisterType((*NodeStat)(nil), "NodeStat")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*AddFileRequest)(nil), "AddFileRequest")
	proto.RegisterType((*AddFileResponse)(nil), "AddFileResponse")
	proto.RegisterType((*GetFileRequest)(nil), "GetFileRequest")
	proto.RegisterType((*GetFileResponse)(nil), "GetFileResponse")
	proto.RegisterType((*AddNodeRequest)(nil), "AddNodeRequest")
	proto.RegisterType((*AddNodeResponse)(nil), "AddNodeResponse")
	proto.RegisterType((*AddNodesRequest)(nil), "AddNodesRequest")
	proto.RegisterType((*AddNodesResponse)(nil), "AddNodesResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "GetNodeResponse")
	proto.RegisterType((*GetNodesRequest)(nil), "GetNodesRequest")
	proto.RegisterType((*GetNodesResponse)(nil), "GetNodesResponse")
	proto.RegisterType((*RemoveNodeRequest)(nil), "RemoveNodeRequest")
	proto.RegisterType((*RemoveNodeResponse)(nil), "RemoveNodeResponse")
	proto.RegisterType((*RemoveNodesRequest)(nil), "RemoveNodesRequest")
	proto.RegisterType((*RemoveNodesResponse)(nil), "RemoveNodesResponse")
	proto.RegisterType((*ResolveLinkRequest)(nil), "ResolveLinkRequest")
	proto.RegisterType((*ResolveLinkResponse)(nil), "ResolveLinkResponse")
	proto.RegisterType((*ResolveRequest)(nil), "ResolveRequest")
	proto.RegisterType((*ResolveResponse)(nil), "ResolveResponse")
	proto.RegisterType((*TreeRequest)(nil), "TreeRequest")
	proto.RegisterType((*TreeResponse)(nil), "TreeResponse")
	proto.RegisterType((*DeleteBlockRequest)(nil), "DeleteBlockRequest")
	proto.RegisterType((*DeleteBlockResponse)(nil), "DeleteBlockResponse")
	proto.RegisterType((*HasBlockRequest)(nil), "HasBlockRequest")
	proto.RegisterType((*HasBlockResponse)(nil), "HasBlockResponse")
	proto.RegisterType((*GetBlockRequest)(nil), "GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "GetBlockResponse")
	proto.RegisterType((*GetBlockSizeRequest)(nil), "GetBlockSizeRequest")
	proto.RegisterType((*GetBlockSizeResponse)(nil), "GetBlockSizeResponse")
	proto.RegisterType((*PutBlockRequest)(nil), "PutBlockRequest")
	proto.RegisterType((*PutBlockResponse)(nil), "PutBlockResponse")
	proto.RegisterType((*PutBlocksRequest)(nil), "PutBlocksRequest")
	proto.RegisterType((*PutBlocksResponse)(nil), "PutBlocksResponse")
	proto.RegisterType((*AllKeysRequest)(nil), "AllKeysRequest")
	proto.RegisterType((*AllKeysResponse)(nil), "AllKeysResponse")
	proto.RegisterType((*HashOnReadRequest)(nil), "HashOnReadRequest")
	proto.RegisterType((*HashOnReadResponse)(nil), "HashOnReadResponse")
}

func init() { proto.RegisterFile("ipfs_lite.proto", fileDescriptor_8edd8ce3e1de43b8) }

var fileDescriptor_8edd8ce3e1de43b8 = []byte{
	// 1202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x6b, 0x6f, 0x1b, 0x45,
	0x17, 0xb6, 0x5f, 0xdf, 0x4f, 0x2e, 0xb6, 0x8f, 0x9d, 0xca, 0xd9, 0xf6, 0x45, 0xd5, 0xd0, 0x94,
	0x08, 0x45, 0x93, 0x34, 0x41, 0x42, 0x42, 0x02, 0x91, 0xb4, 0x6a, 0x83, 0x88, 0x4a, 0xba, 0x45,
	0x7c, 0xad, 0x26, 0xde, 0x49, 0xbc, 0x64, 0xbd, 0x6b, 0xbc, 0xe3, 0x94, 0xf0, 0xd3, 0x90, 0xf8,
	0x4d, 0xfc, 0x05, 0x34, 0xd7, 0xbd, 0xd8, 0x75, 0xab, 0x7e, 0xdb, 0x73, 0x7b, 0xce, 0x33, 0x67,
	0x3c, 0xcf, 0x91, 0xa1, 0x1b, 0xce, 0xae, 0xd3, 0x77, 0x51, 0x28, 0x38, 0x9d, 0xcd, 0x13, 0x91,
	0x78, 0xbb, 0x37, 0x49, 0x72, 0x13, 0xf1, 0x43, 0x65, 0x5d, 0x2d, 0xae, 0x0f, 0x59, 0x7c, 0xaf,
	0x43, 0xe4, 0x9f, 0x2a, 0x74, 0x4e, 0x83, 0xe0, 0x92, 0xcd, 0xd9, 0x34, 0xc5, 0x07, 0xd0, 0x8c,
	0xd8, 0x7d, 0xb2, 0x10, 0xa3, 0xea, 0xe3, 0xea, 0x7e, 0xc7, 0x37, 0x16, 0x8e, 0xa0, 0x35, 0x9e,
	0x2c, 0xe2, 0x5b, 0x3e, 0x1f, 0xfd, 0x4f, 0x05, 0xac, 0x89, 0x8f, 0xa0, 0x33, 0x67, 0xef, 0x2f,
	0x38, 0xbb, 0xe3, 0xe9, 0xa8, 0xf6, 0xb8, 0xba, 0xdf, 0xf6, 0x33, 0x87, 0xc4, 0x9b, 0x84, 0x41,
	0xc0, 0xe3, 0x51, 0x5d, 0x85, 0x8c, 0x25, 0xfd, 0xe9, 0x84, 0xcd, 0x79, 0x30, 0x6a, 0x68, 0xbf,
	0xb6, 0xa4, 0x3f, 0x4e, 0x9e, 0x27, 0xb3, 0xfb, 0x51, 0x53, 0xfb, 0xb5, 0x25, 0xfb, 0x4f, 0x58,
	0x3a, 0x79, 0xb9, 0x88, 0x47, 0x2d, 0xdd, 0xdf, 0x98, 0xe4, 0x04, 0x1a, 0x67, 0x51, 0x32, 0xbe,
	0x95, 0x29, 0x73, 0xf6, 0xfe, 0x05, 0x13, 0x4c, 0x71, 0xdf, 0xf4, 0xad, 0x89, 0x3d, 0xa8, 0x8d,
	0xc3, 0xc0, 0x10, 0x97, 0x9f, 0xe4, 0x47, 0xa8, 0x5f, 0x84, 0xf1, 0x2d, 0x22, 0xd4, 0x63, 0x36,
	0xe5, 0xe6, 0xb0, 0xea, 0x5b, 0xfa, 0xd2, 0xf0, 0x2f, 0xae, 0xd2, 0x6b, 0xbe, 0xfa, 0xb6, 0x08,
	0xb5, 0x0c, 0xe1, 0xef, 0x2a, 0xb4, 0x5f, 0x27, 0x01, 0x7f, 0x2b, 0x98, 0x90, 0x25, 0x92, 0x8e,
	0x85, 0x91, 0xdf, 0xe8, 0x41, 0x3b, 0x5e, 0x4c, 0x65, 0x97, 0x54, 0x41, 0x35, 0x7c, 0x67, 0xcb,
	0x99, 0x5d, 0x49, 0xce, 0x6f, 0x65, 0x9f, 0x9a, 0x0a, 0x66, 0x0e, 0x19, 0x8d, 0x64, 0x9a, 0x8a,
	0xd6, 0x75, 0xd4, 0x39, 0x24, 0x6e, 0xc0, 0x04, 0x53, 0xc1, 0x86, 0xc6, 0xb5, 0x36, 0x3e, 0x85,
	0xed, 0xf1, 0x62, 0xba, 0x88, 0x98, 0x08, 0xef, 0xb8, 0xca, 0x68, 0xaa, 0x8c, 0x92, 0x97, 0x08,
	0xa8, 0x4b, 0xee, 0xf8, 0x08, 0x1a, 0xaa, 0xad, 0x22, 0xbe, 0x71, 0xdc, 0xa4, 0x6a, 0x92, 0xbe,
	0x76, 0xe2, 0x43, 0x68, 0x44, 0x86, 0x7e, 0x6d, 0x7f, 0xe3, 0xb8, 0x41, 0x25, 0x79, 0x5f, 0xfb,
	0xf0, 0xff, 0x50, 0x4f, 0x05, 0x13, 0x8a, 0xfd, 0xc6, 0x71, 0x87, 0xda, 0x59, 0xf8, 0xca, 0xed,
	0x86, 0x58, 0xcf, 0x86, 0x48, 0x5e, 0xc3, 0xf6, 0x69, 0x10, 0xbc, 0x0c, 0x23, 0xee, 0xf3, 0x3f,
	0x16, 0x3c, 0x15, 0xb8, 0x0f, 0x1d, 0x66, 0x7f, 0x7a, 0x86, 0x03, 0x50, 0xf7, 0x63, 0xf4, 0xb3,
	0xa0, 0xc4, 0x93, 0xa7, 0x54, 0x93, 0xdc, 0xf4, 0xd5, 0x37, 0x39, 0x80, 0xae, 0xc3, 0x4b, 0x67,
	0x49, 0x9c, 0x72, 0xdc, 0x85, 0x7a, 0x9c, 0x04, 0xdc, 0x60, 0x35, 0x14, 0x2b, 0x5f, 0xb9, 0x08,
	0x81, 0xed, 0x57, 0x5c, 0xe4, 0xbb, 0x9b, 0x4b, 0xad, 0x66, 0x97, 0xba, 0x07, 0x5d, 0x97, 0x63,
	0x10, 0x6d, 0xe3, 0x6a, 0xae, 0x31, 0x55, 0x07, 0x51, 0xd8, 0x06, 0x6a, 0xed, 0x20, 0x49, 0x5f,
	0x11, 0xd5, 0xf9, 0x1a, 0x96, 0x3c, 0x73, 0xae, 0xd4, 0x62, 0x7c, 0x01, 0x4d, 0x95, 0x2e, 0x27,
	0x51, 0xcb, 0x81, 0x18, 0x2f, 0x41, 0xe8, 0x65, 0x25, 0x06, 0x46, 0x1f, 0x2a, 0xcf, 0x64, 0xf9,
	0x50, 0x07, 0xea, 0x50, 0xf9, 0xee, 0xeb, 0xc6, 0xb4, 0xe7, 0xb2, 0x1d, 0x31, 0x84, 0xfa, 0x38,
	0x0c, 0x34, 0xad, 0x8e, 0xaf, 0xbe, 0xc9, 0x1b, 0xe8, 0x65, 0x69, 0x06, 0xf5, 0xe1, 0x0a, 0xd4,
	0xf3, 0x8a, 0xc6, 0xc5, 0x07, 0xd0, 0xe0, 0xf3, 0x79, 0x62, 0xe4, 0xe3, 0xbc, 0xe2, 0x6b, 0xf3,
	0xac, 0x0d, 0xcd, 0x64, 0x26, 0xc2, 0x24, 0x26, 0x7b, 0xd0, 0xf7, 0xf9, 0x34, 0xb9, 0xe3, 0xeb,
	0x8f, 0x33, 0x04, 0xcc, 0xa7, 0x99, 0x41, 0xec, 0xe7, 0xbd, 0x6b, 0x99, 0xef, 0xc0, 0xa0, 0x90,
	0x69, 0x00, 0xce, 0x24, 0x40, 0x9a, 0x44, 0x77, 0x5c, 0xfd, 0xca, 0x0d, 0xc0, 0x08, 0x5a, 0x92,
	0xfd, 0x73, 0x47, 0xc1, 0x9a, 0x12, 0x7a, 0xc6, 0xc4, 0x44, 0xbd, 0x8d, 0x8e, 0xaf, 0xbe, 0xc9,
	0x6f, 0x12, 0x3a, 0x87, 0x91, 0x4d, 0x5b, 0xbe, 0x19, 0x37, 0x17, 0x15, 0x54, 0x2e, 0x7c, 0x02,
	0x5b, 0x73, 0x3e, 0x65, 0x61, 0x1c, 0xc6, 0x37, 0x97, 0x19, 0x5c, 0xd1, 0x49, 0x7e, 0x80, 0x6d,
	0x83, 0xfb, 0x79, 0xbc, 0x38, 0x74, 0x5d, 0xbd, 0xe1, 0x74, 0x00, 0xcd, 0xe4, 0xea, 0x77, 0x3e,
	0x16, 0x86, 0xd5, 0x90, 0xea, 0x0d, 0x41, 0xed, 0x86, 0xa0, 0xa7, 0xf1, 0xbd, 0x6f, 0x72, 0x3e,
	0x91, 0xe6, 0x1b, 0xd8, 0xf8, 0x75, 0xce, 0x3f, 0x8f, 0x23, 0x0e, 0xa1, 0x11, 0xf0, 0x99, 0x98,
	0x18, 0x39, 0xd4, 0x06, 0x79, 0x02, 0x9b, 0x1a, 0xd2, 0xd0, 0x1e, 0x42, 0x43, 0x66, 0xdb, 0x1b,
	0xd5, 0x06, 0x79, 0x0a, 0xf8, 0x82, 0x47, 0x5c, 0x70, 0xfd, 0x60, 0x3e, 0xf8, 0xd3, 0xd9, 0x81,
	0x41, 0x21, 0xcf, 0x5c, 0xfd, 0x97, 0xd0, 0x3d, 0x67, 0xe9, 0x47, 0x6a, 0x29, 0xf4, 0xb2, 0x24,
	0xc3, 0xc6, 0x83, 0xf6, 0xc4, 0xf8, 0x54, 0x6a, 0xdb, 0x77, 0xb6, 0x04, 0x7d, 0xc5, 0xc5, 0x47,
	0x40, 0x8f, 0xd4, 0x2b, 0x2a, 0x82, 0xae, 0x97, 0x92, 0xaf, 0x60, 0x60, 0x2b, 0xa4, 0x92, 0x7f,
	0x18, 0xfa, 0x6b, 0x18, 0x16, 0x13, 0x33, 0x3d, 0x53, 0xc2, 0x5c, 0x55, 0x63, 0xd6, 0xc2, 0x7c,
	0x08, 0xdd, 0xcb, 0x45, 0x91, 0xeb, 0x7a, 0x16, 0x08, 0xbd, 0xac, 0xc0, 0x4c, 0xf1, 0x38, 0xf3,
	0x7d, 0xb2, 0xa4, 0x0d, 0xa0, 0x9f, 0xab, 0x31, 0x40, 0x3d, 0xd8, 0x3e, 0x8d, 0xa2, 0x9f, 0xf9,
	0xbd, 0x85, 0x91, 0xb3, 0x74, 0x1e, 0x73, 0x8c, 0xe5, 0x03, 0x9f, 0x40, 0xff, 0x9c, 0xa5, 0x93,
	0x5f, 0x62, 0x9f, 0xb3, 0x20, 0x23, 0x00, 0x13, 0xe7, 0x34, 0x77, 0x94, 0xf3, 0x48, 0x31, 0xc9,
	0x17, 0x69, 0xf0, 0xe3, 0x7f, 0x5b, 0xd0, 0xfe, 0x69, 0x76, 0x9d, 0x5e, 0x84, 0x82, 0x23, 0x85,
	0x96, 0xd9, 0x32, 0xd8, 0xa5, 0xc5, 0xfd, 0xe5, 0xf5, 0x68, 0x69, 0x01, 0x91, 0x8a, 0xcc, 0x37,
	0x3b, 0x04, 0xbb, 0xb4, 0xb8, 0x71, 0xbc, 0x1e, 0x2d, 0xad, 0x17, 0x9d, 0x6f, 0x64, 0x5d, 0xe3,
	0xe7, 0xd4, 0x4f, 0xe3, 0x17, 0x74, 0xae, 0x82, 0xcf, 0xa0, 0x6d, 0xd7, 0x00, 0xba, 0xb8, 0x1d,
	0x95, 0xd7, 0xa7, 0x4b, 0x3b, 0xc2, 0x52, 0x32, 0x2d, 0x8a, 0xfb, 0x42, 0x53, 0x2a, 0xb5, 0x38,
	0x81, 0xb6, 0x15, 0x77, 0x74, 0xf1, 0x5c, 0x8b, 0xb2, 0xf2, 0x93, 0xca, 0x51, 0x15, 0xbf, 0x05,
	0xc8, 0x74, 0x15, 0x91, 0x2e, 0x69, 0xb9, 0x37, 0xa0, 0x2b, 0x84, 0xbb, 0x82, 0xdf, 0xc1, 0x46,
	0x4e, 0x90, 0x31, 0x9f, 0xe5, 0x7a, 0x0e, 0xe9, 0x2a, 0xcd, 0x36, 0xb5, 0x4e, 0x71, 0x55, 0x6d,
	0x59, 0xc3, 0x55, 0xed, 0x92, 0x28, 0xeb, 0xa9, 0x98, 0x00, 0x76, 0x69, 0x51, 0x5f, 0xbd, 0x1e,
	0x2d, 0x09, 0x26, 0xa9, 0xe0, 0x1e, 0xd4, 0xa5, 0x16, 0xe1, 0x26, 0xcd, 0xa9, 0x9c, 0xb7, 0x45,
	0xf3, 0x02, 0xa5, 0x29, 0xe5, 0x44, 0x06, 0x07, 0x74, 0x59, 0x9a, 0xbc, 0x21, 0x5d, 0xa5, 0x43,
	0xea, 0x6e, 0xad, 0xc8, 0x60, 0x8f, 0x96, 0x44, 0xc9, 0xeb, 0xd3, 0xb2, 0x02, 0xe9, 0x12, 0xfb,
	0xce, 0xf5, 0x5d, 0x95, 0x4a, 0xca, 0xfa, 0x42, 0x2a, 0xf8, 0x3d, 0x6c, 0xe6, 0xa5, 0x01, 0x87,
	0x74, 0x85, 0xa4, 0x78, 0x3b, 0x74, 0x95, 0x7e, 0xe8, 0x8e, 0xf6, 0xd1, 0x62, 0x8f, 0x96, 0x84,
	0xc3, 0xeb, 0xd3, 0x25, 0x65, 0xa8, 0xe0, 0x37, 0xd0, 0x71, 0xef, 0x1c, 0xb3, 0x0c, 0x77, 0xbd,
	0x48, 0x97, 0x65, 0xa0, 0x82, 0x47, 0xd0, 0x32, 0xcf, 0x5e, 0xbe, 0x8c, 0x82, 0x24, 0xc8, 0x97,
	0x51, 0x54, 0x04, 0xfb, 0x1b, 0xcc, 0x9e, 0x33, 0x22, 0x5d, 0x12, 0x04, 0x6f, 0x40, 0x97, 0xdf,
	0x3b, 0xa9, 0x9c, 0x1d, 0xc0, 0x6e, 0x98, 0x50, 0xc1, 0xff, 0x14, 0x61, 0xc4, 0xe9, 0xcd, 0x7c,
	0x36, 0x7e, 0xe7, 0xfe, 0x42, 0x9d, 0x6d, 0x59, 0x2d, 0xb8, 0x94, 0xbb, 0xf1, 0xb2, 0x7a, 0xd5,
	0x54, 0x4b, 0xf2, 0xe4, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x4c, 0xa2, 0xea, 0x67, 0x0d,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IpfsLiteClient is the client API for IpfsLite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IpfsLiteClient interface {
	AddFile(ctx context.Context, in *AddFileRequest, opts ...grpc.CallOption) (*AddFileResponse, error)
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*AddNodeResponse, error)
	AddNodes(ctx context.Context, in *AddNodesRequest, opts ...grpc.CallOption) (*AddNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (IpfsLite_GetNodesClient, error)
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error)
	RemoveNodes(ctx context.Context, in *RemoveNodesRequest, opts ...grpc.CallOption) (*RemoveNodesResponse, error)
	ResolveLink(ctx context.Context, in *ResolveLinkRequest, opts ...grpc.CallOption) (*ResolveLinkResponse, error)
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	Tree(ctx context.Context, in *TreeRequest, opts ...grpc.CallOption) (*TreeResponse, error)
	DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*DeleteBlockResponse, error)
	HasBlock(ctx context.Context, in *HasBlockRequest, opts ...grpc.CallOption) (*HasBlockResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	GetBlockSize(ctx context.Context, in *GetBlockSizeRequest, opts ...grpc.CallOption) (*GetBlockSizeResponse, error)
	PutBlock(ctx context.Context, in *PutBlockRequest, opts ...grpc.CallOption) (*PutBlockResponse, error)
	PutBlocks(ctx context.Context, in *PutBlocksRequest, opts ...grpc.CallOption) (*PutBlocksResponse, error)
	AllKeys(ctx context.Context, in *AllKeysRequest, opts ...grpc.CallOption) (IpfsLite_AllKeysClient, error)
	HashOnRead(ctx context.Context, in *HashOnReadRequest, opts ...grpc.CallOption) (*HashOnReadResponse, error)
}

type ipfsLiteClient struct {
	cc *grpc.ClientConn
}

func NewIpfsLiteClient(cc *grpc.ClientConn) IpfsLiteClient {
	return &ipfsLiteClient{cc}
}

func (c *ipfsLiteClient) AddFile(ctx context.Context, in *AddFileRequest, opts ...grpc.CallOption) (*AddFileResponse, error) {
	out := new(AddFileResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/AddFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) AddNode(ctx context.Context, in *AddNodeRequest, opts ...grpc.CallOption) (*AddNodeResponse, error) {
	out := new(AddNodeResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) AddNodes(ctx context.Context, in *AddNodesRequest, opts ...grpc.CallOption) (*AddNodesResponse, error) {
	out := new(AddNodesResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/AddNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (IpfsLite_GetNodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IpfsLite_serviceDesc.Streams[0], "/IpfsLite/GetNodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &ipfsLiteGetNodesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IpfsLite_GetNodesClient interface {
	Recv() (*GetNodesResponse, error)
	grpc.ClientStream
}

type ipfsLiteGetNodesClient struct {
	grpc.ClientStream
}

func (x *ipfsLiteGetNodesClient) Recv() (*GetNodesResponse, error) {
	m := new(GetNodesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ipfsLiteClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*RemoveNodeResponse, error) {
	out := new(RemoveNodeResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) RemoveNodes(ctx context.Context, in *RemoveNodesRequest, opts ...grpc.CallOption) (*RemoveNodesResponse, error) {
	out := new(RemoveNodesResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/RemoveNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) ResolveLink(ctx context.Context, in *ResolveLinkRequest, opts ...grpc.CallOption) (*ResolveLinkResponse, error) {
	out := new(ResolveLinkResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/ResolveLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/Resolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) Tree(ctx context.Context, in *TreeRequest, opts ...grpc.CallOption) (*TreeResponse, error) {
	out := new(TreeResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/Tree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) DeleteBlock(ctx context.Context, in *DeleteBlockRequest, opts ...grpc.CallOption) (*DeleteBlockResponse, error) {
	out := new(DeleteBlockResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/DeleteBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) HasBlock(ctx context.Context, in *HasBlockRequest, opts ...grpc.CallOption) (*HasBlockResponse, error) {
	out := new(HasBlockResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/HasBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) GetBlockSize(ctx context.Context, in *GetBlockSizeRequest, opts ...grpc.CallOption) (*GetBlockSizeResponse, error) {
	out := new(GetBlockSizeResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/GetBlockSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) PutBlock(ctx context.Context, in *PutBlockRequest, opts ...grpc.CallOption) (*PutBlockResponse, error) {
	out := new(PutBlockResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/PutBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) PutBlocks(ctx context.Context, in *PutBlocksRequest, opts ...grpc.CallOption) (*PutBlocksResponse, error) {
	out := new(PutBlocksResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/PutBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsLiteClient) AllKeys(ctx context.Context, in *AllKeysRequest, opts ...grpc.CallOption) (IpfsLite_AllKeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IpfsLite_serviceDesc.Streams[1], "/IpfsLite/AllKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &ipfsLiteAllKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IpfsLite_AllKeysClient interface {
	Recv() (*AllKeysResponse, error)
	grpc.ClientStream
}

type ipfsLiteAllKeysClient struct {
	grpc.ClientStream
}

func (x *ipfsLiteAllKeysClient) Recv() (*AllKeysResponse, error) {
	m := new(AllKeysResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ipfsLiteClient) HashOnRead(ctx context.Context, in *HashOnReadRequest, opts ...grpc.CallOption) (*HashOnReadResponse, error) {
	out := new(HashOnReadResponse)
	err := c.cc.Invoke(ctx, "/IpfsLite/HashOnRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpfsLiteServer is the server API for IpfsLite service.
type IpfsLiteServer interface {
	AddFile(context.Context, *AddFileRequest) (*AddFileResponse, error)
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	AddNode(context.Context, *AddNodeRequest) (*AddNodeResponse, error)
	AddNodes(context.Context, *AddNodesRequest) (*AddNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	GetNodes(*GetNodesRequest, IpfsLite_GetNodesServer) error
	RemoveNode(context.Context, *RemoveNodeRequest) (*RemoveNodeResponse, error)
	RemoveNodes(context.Context, *RemoveNodesRequest) (*RemoveNodesResponse, error)
	ResolveLink(context.Context, *ResolveLinkRequest) (*ResolveLinkResponse, error)
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	Tree(context.Context, *TreeRequest) (*TreeResponse, error)
	DeleteBlock(context.Context, *DeleteBlockRequest) (*DeleteBlockResponse, error)
	HasBlock(context.Context, *HasBlockRequest) (*HasBlockResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	GetBlockSize(context.Context, *GetBlockSizeRequest) (*GetBlockSizeResponse, error)
	PutBlock(context.Context, *PutBlockRequest) (*PutBlockResponse, error)
	PutBlocks(context.Context, *PutBlocksRequest) (*PutBlocksResponse, error)
	AllKeys(*AllKeysRequest, IpfsLite_AllKeysServer) error
	HashOnRead(context.Context, *HashOnReadRequest) (*HashOnReadResponse, error)
}

// UnimplementedIpfsLiteServer can be embedded to have forward compatible implementations.
type UnimplementedIpfsLiteServer struct {
}

func (*UnimplementedIpfsLiteServer) AddFile(ctx context.Context, req *AddFileRequest) (*AddFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFile not implemented")
}
func (*UnimplementedIpfsLiteServer) GetFile(ctx context.Context, req *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (*UnimplementedIpfsLiteServer) AddNode(ctx context.Context, req *AddNodeRequest) (*AddNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (*UnimplementedIpfsLiteServer) AddNodes(ctx context.Context, req *AddNodesRequest) (*AddNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNodes not implemented")
}
func (*UnimplementedIpfsLiteServer) GetNode(ctx context.Context, req *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (*UnimplementedIpfsLiteServer) GetNodes(req *GetNodesRequest, srv IpfsLite_GetNodesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (*UnimplementedIpfsLiteServer) RemoveNode(ctx context.Context, req *RemoveNodeRequest) (*RemoveNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}
func (*UnimplementedIpfsLiteServer) RemoveNodes(ctx context.Context, req *RemoveNodesRequest) (*RemoveNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNodes not implemented")
}
func (*UnimplementedIpfsLiteServer) ResolveLink(ctx context.Context, req *ResolveLinkRequest) (*ResolveLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveLink not implemented")
}
func (*UnimplementedIpfsLiteServer) Resolve(ctx context.Context, req *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (*UnimplementedIpfsLiteServer) Tree(ctx context.Context, req *TreeRequest) (*TreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tree not implemented")
}
func (*UnimplementedIpfsLiteServer) DeleteBlock(ctx context.Context, req *DeleteBlockRequest) (*DeleteBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBlock not implemented")
}
func (*UnimplementedIpfsLiteServer) HasBlock(ctx context.Context, req *HasBlockRequest) (*HasBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasBlock not implemented")
}
func (*UnimplementedIpfsLiteServer) GetBlock(ctx context.Context, req *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (*UnimplementedIpfsLiteServer) GetBlockSize(ctx context.Context, req *GetBlockSizeRequest) (*GetBlockSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockSize not implemented")
}
func (*UnimplementedIpfsLiteServer) PutBlock(ctx context.Context, req *PutBlockRequest) (*PutBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutBlock not implemented")
}
func (*UnimplementedIpfsLiteServer) PutBlocks(ctx context.Context, req *PutBlocksRequest) (*PutBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutBlocks not implemented")
}
func (*UnimplementedIpfsLiteServer) AllKeys(req *AllKeysRequest, srv IpfsLite_AllKeysServer) error {
	return status.Errorf(codes.Unimplemented, "method AllKeys not implemented")
}
func (*UnimplementedIpfsLiteServer) HashOnRead(ctx context.Context, req *HashOnReadRequest) (*HashOnReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HashOnRead not implemented")
}

func RegisterIpfsLiteServer(s *grpc.Server, srv IpfsLiteServer) {
	s.RegisterService(&_IpfsLite_serviceDesc, srv)
}

func _IpfsLite_AddFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).AddFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/AddFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).AddFile(ctx, req.(*AddFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).AddNode(ctx, req.(*AddNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_AddNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).AddNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/AddNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).AddNodes(ctx, req.(*AddNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_GetNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNodesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IpfsLiteServer).GetNodes(m, &ipfsLiteGetNodesServer{stream})
}

type IpfsLite_GetNodesServer interface {
	Send(*GetNodesResponse) error
	grpc.ServerStream
}

type ipfsLiteGetNodesServer struct {
	grpc.ServerStream
}

func (x *ipfsLiteGetNodesServer) Send(m *GetNodesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IpfsLite_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_RemoveNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).RemoveNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/RemoveNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).RemoveNodes(ctx, req.(*RemoveNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_ResolveLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).ResolveLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/ResolveLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).ResolveLink(ctx, req.(*ResolveLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_Tree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).Tree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/Tree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).Tree(ctx, req.(*TreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_DeleteBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).DeleteBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/DeleteBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).DeleteBlock(ctx, req.(*DeleteBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_HasBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).HasBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/HasBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).HasBlock(ctx, req.(*HasBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_GetBlockSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).GetBlockSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/GetBlockSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).GetBlockSize(ctx, req.(*GetBlockSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_PutBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).PutBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/PutBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).PutBlock(ctx, req.(*PutBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_PutBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).PutBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/PutBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).PutBlocks(ctx, req.(*PutBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsLite_AllKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IpfsLiteServer).AllKeys(m, &ipfsLiteAllKeysServer{stream})
}

type IpfsLite_AllKeysServer interface {
	Send(*AllKeysResponse) error
	grpc.ServerStream
}

type ipfsLiteAllKeysServer struct {
	grpc.ServerStream
}

func (x *ipfsLiteAllKeysServer) Send(m *AllKeysResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IpfsLite_HashOnRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashOnReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsLiteServer).HashOnRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IpfsLite/HashOnRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsLiteServer).HashOnRead(ctx, req.(*HashOnReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IpfsLite_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IpfsLite",
	HandlerType: (*IpfsLiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFile",
			Handler:    _IpfsLite_AddFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _IpfsLite_GetFile_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _IpfsLite_AddNode_Handler,
		},
		{
			MethodName: "AddNodes",
			Handler:    _IpfsLite_AddNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _IpfsLite_GetNode_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _IpfsLite_RemoveNode_Handler,
		},
		{
			MethodName: "RemoveNodes",
			Handler:    _IpfsLite_RemoveNodes_Handler,
		},
		{
			MethodName: "ResolveLink",
			Handler:    _IpfsLite_ResolveLink_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _IpfsLite_Resolve_Handler,
		},
		{
			MethodName: "Tree",
			Handler:    _IpfsLite_Tree_Handler,
		},
		{
			MethodName: "DeleteBlock",
			Handler:    _IpfsLite_DeleteBlock_Handler,
		},
		{
			MethodName: "HasBlock",
			Handler:    _IpfsLite_HasBlock_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _IpfsLite_GetBlock_Handler,
		},
		{
			MethodName: "GetBlockSize",
			Handler:    _IpfsLite_GetBlockSize_Handler,
		},
		{
			MethodName: "PutBlock",
			Handler:    _IpfsLite_PutBlock_Handler,
		},
		{
			MethodName: "PutBlocks",
			Handler:    _IpfsLite_PutBlocks_Handler,
		},
		{
			MethodName: "HashOnRead",
			Handler:    _IpfsLite_HashOnRead_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNodes",
			Handler:       _IpfsLite_GetNodes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AllKeys",
			Handler:       _IpfsLite_AllKeys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ipfs_lite.proto",
}
